aws_credebtials_environment_variables:
  Access_key_ID: AWS_ACCESS_KEY_ID
  Secret_access_key: AWS_SECRET_ACCESS_KEY
feature_store:
  bucket_name: fitbit-data-registry
  model_bucket: fitbit-prod-models
trainig_configurations:
  training_batch_files_path: Training_Batch_Files
  schema_path: schema_training.json
  table_name: Training
  dropUnnecessaryColumns:
    - Id
    - ActivityDate
    - TotalDistance
    - TrackerDistance
  label_column_name: Calories
  kmeans:
    random_state: 42
    max_range_vale: 11
    elbow_plot_path_to_save: preprocessing_data/K-Means_Elbow.PNG
    KneeLocator:
      curve: convex
      direction: decreasing
  train_test_split:
    test_size: 0.2
    random_state: 0
  KNNImputer: 
    n_neighbors: 3
    weights: uniform
  GridSearchCV:
    cv: 5
    verbose: 3
  random_forest: 
    param_grid:
      {"n_estimators": [10, 50, 100, 130], "bootstrap": [True, False],
                                "min_samples_split" : [2, 5, 10],
                                "min_samples_leaf" : [1, 2, 4],
                                "max_features": ["auto", "sqrt","log2"]}
  decision_tree:
    param_grid : {"criterion": ["mse", "friedman_mse", "mae"],
                              "splitter": ["best", "random"],
                              "max_features": ["auto", "sqrt", "log2"],
                              }
  xg_boost:
    param_grid : {'learning_rate': [0.5, 0.1, 0.01, 0.001],
                'max_depth': [3, 5, 10, 20],
                'n_estimators': [10, 50, 100, 200]}
  models_directory: models

predictions_configurations: 
  predictions_batch_files_path: Prediction_Batch_files
